In [36]:
import numpy as np


In [37]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [38]:
list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [41]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [43]:
np.ones(100,int)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
####Create an array of zeros with 2 rows and 10 coloumns

In [45]:
arr1=np.array[np.zeros(10),np.zeros(10)]  

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
arr1=np.array([np.zeros(10),np.zeros(10)])

In [ ]:
arr1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np

<module 'numpy' from 'C:\\Users\\hp\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python310\\site-packages\\numpy\\__init__.py'>

In [ ]:
numpy

NameError: name 'numpy' is not defined

In [ ]:
np.random.randn(3,2)

array([[-0.95553697,  0.50888183],
       [ 1.01610128,  0.44147023],
       [ 1.48242493, -0.27982161]])

In [ ]:
np.random.randint(20,56,100)

array([32, 22, 55, 35, 47, 51, 30, 46, 40, 33, 21, 38, 23, 45, 35, 45, 30,
       32, 29, 42, 40, 20, 20, 37, 22, 53, 50, 38, 53, 45, 44, 21, 34, 43,
       45, 53, 28, 51, 35, 51, 29, 26, 30, 33, 38, 50, 21, 49, 40, 29, 20,
       54, 55, 21, 34, 28, 43, 29, 43, 51, 29, 55, 51, 47, 41, 49, 34, 44,
       51, 26, 25, 33, 27, 41, 23, 21, 29, 24, 26, 32, 46, 39, 54, 43, 51,
       30, 41, 46, 29, 26, 41, 20, 27, 24, 35, 38, 32, 29, 43, 37])

In [ ]:
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array=np.random.randint(0,100,20)
rand_array


array([68, 69, 51, 42, 95,  1, 63, 56,  4, 17, 80, 31, 66, 39, 10, 64, 42,
       46, 49, 41])

In [ ]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.max()

95

In [46]:
rand_array.min()

1

In [47]:
rand_array.argmin()

5

In [48]:
sample_array.dtype

dtype('int32')

In [49]:
a=np.eye(5)

In [50]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
#Two dimensional array

In [54]:
import numpy as np


In [56]:
sample_matrix=np.array(([[1,2,3],[4,5,6],[7,8,9]]))

In [57]:
sample_matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
sample_array[0][2]

IndexError: invalid index to scalar variable.

In [59]:
sample_matrix[0][2]

3

In [60]:
sample_matrix[2,:]

array([7, 8, 9])